language: cpp
compiler: gcc
dist: trusty
sudo: required
cache:
    directories:
        - $HOME/apt_mingw_cache
        - $HOME/.ccache
        - $HOME/pbuilder-bases
matrix:
    include:
        - os: linux
        - env:
            - secure: "cEEIQAF6Qz1WPhqEGOMaC569/Nu3LyXkAyODqYrmCj1i6w35Z61Jr7hguQTsTfVNPi11843QxIMZohXFhADLgeQL6URhXJ2eZdxO4WA8LPCAFrPj3uMHOIm7vfpj1wfBTOzDfEzs6K5OAfWvDJc/DeWF+S4j+AxE9lO6jAGP9nn+93f4NL96lxdqksHW/FdOkeyGdDf9JePOCZFIIuGTSdeVQQkkbRCt2eny1WWOJoxS/+L0WM2DSQkOgd6OgZ+Ai/3kzb3KbUoKvQz5ILZQzQi3JwbcdbY2SxS6wBC2BCHmnJcUo3yal6UIONJRxEMeCfCSN+rxwYIe4hBXL8iHfDFTNCy6xLi1Kj/YavO87d59VyqLp17w4zPfS6vxlPtoqvwJqvlPacITM/cmKBw0sFu3DSpnAhm6QHTsnzkcbmyS8JMQU+n4RBvhTQeMPuSF9AEKpO7W2pvuaLAGE4ROPJHEOn4bX1Q6g35K8KymUU2OECXmqEv09HCDAH089lj9EfrfcETBRRxYZxsy57JL6lUGt+8sJl/LtDlVA0wkOSN3pV7tCO7jcXjTPlUKlOVzwp5vAd5MOjNpQfdfRl1gBzgNa3kH21IAuprIb5f8iCiX0SruT/46PmUXjad/bCUfuCtzbETGNLERGEYudcoLtc06IXRol1TU2jbVv3tOg24="
            - secure: "ZE6K8rOeNFfP7wh/xhVEvM0bBfZ9mi+xuWDcvP+9E0vWZNDymK/a+6av/xS+bf5ZeQxe8WDN20PVQFnXgdF+XyFLnSPREjLzTMYwFIvXY6USPuIyBlcCL5xETdBpVHAAZOHW6/N8TJRE75bZBDJ5YcQxI1iwNg7G9UF78bX8yM504SsQhHpADBSWU6sOLFMmQYPO8SW8fjyCY90gURsqeiZRP8elCfDAgmI5gJnaHDT7X40IdZ2lYQRAaeB5WqrS8vV56NU52UREmQs8tz96YCqOn7VLd5grVp5g1POlGXKD2M+P8WL9TfSLF8ubprpjJIBchsVxo5rzrCGS6+XZKi8H9qie1LnIRWncCoZ/7WnDE/4au/T9/RC/Ygx3aPwR9FezMFP4qh8mUVYcQYhKakXekWl4sCqeu3IiGoYFQfNol7aC/QCAm2e/xI+NvhWOwb8XFMaLmVDxnpcJg2vKDTgBogurEr+i8Py4P5El+DCshF3jdKOXaukrz9px1IgIVolXs/VzaZ+ajh3aklKsIL80creKy0K6zvU5jCr9vEtEN4rI9nHUQO2ix+eAqZafQSL5JvQrxY57fXczYj7bECzEgx/DX37kXO0wfbMVrPd7B+bVE6dzExccGj6P+ZvzjGULX+hEJlglIj/D0TQX9UF6RlSmAAQxkQP6ljTmsec="
install: ${TRAVIS_BUILD_DIR}/.travis/install.sh
script: ${TRAVIS_BUILD_DIR}/.travis/script.sh
after_script: ${TRAVIS_BUILD_DIR}/.travis/after_script.sh
before_deploy:
    - if [ "$TARGET_OS" != debian-sid ]; then make package; fi
