language: cpp
compiler: gcc
dist: trusty
sudo: required
cache:
    directories:
        - $HOME/apt_mingw_cache
        - $HOME/.ccache
        - $HOME/pbuilder-bases
matrix:
    include:
        - os: linux
branches:
  only:
  - recording_rebased_to_master
